/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author melin
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVentanaFuncion = new javax.swing.JButton();
        btnVentanaBoleto = new javax.swing.JButton();
        btnVentanaPeliculas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnVentanaBoleto1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentanaFuncion.setBackground(new java.awt.Color(0, 204, 102));
        btnVentanaFuncion.setText("Funciones");
        btnVentanaFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaFuncionActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentanaFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, -1));

        btnVentanaBoleto.setBackground(new java.awt.Color(204, 102, 0));
        btnVentanaBoleto.setText("Boletos");
        btnVentanaBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaBoletoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentanaBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, -1));

        btnVentanaPeliculas.setBackground(new java.awt.Color(255, 204, 51));
        btnVentanaPeliculas.setText("Peliculas");
        btnVentanaPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaPeliculasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentanaPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, -1));

        btnSalir.setBackground(new java.awt.Color(0, 102, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/imagenes/MainMenu.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 350));

        btnVentanaBoleto1.setBackground(new java.awt.Color(204, 102, 0));
        btnVentanaBoleto1.setText("Boletos");
        btnVentanaBoleto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaBoleto1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentanaBoleto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentanaBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaBoletoActionPerformed
        CompraBoletosWindow boletos = new CompraBoletosWindow();
        boletos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaBoletoActionPerformed

    private void btnVentanaPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaPeliculasActionPerformed
        VistasCartelera cartelera = new VistasCartelera();
        cartelera.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaPeliculasActionPerformed

    private void btnVentanaFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaFuncionActionPerformed
        FuncionesWindow funcion = new FuncionesWindow();
        funcion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaFuncionActionPerformed

    private void btnVentanaBoleto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaBoleto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentanaBoleto1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVentanaBoleto;
    private javax.swing.JButton btnVentanaBoleto1;
    private javax.swing.JButton btnVentanaFuncion;
    private javax.swing.JButton btnVentanaPeliculas;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
