/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author melin
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVentanaFuncion = new javax.swing.JButton();
        btnVentanaClientes = new javax.swing.JButton();
        btnVentanaBoleto = new javax.swing.JButton();
        btnVentanaPeliculas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentanaFuncion.setBackground(new java.awt.Color(0, 204, 102));
        btnVentanaFuncion.setText("Funciones");
        btnVentanaFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaFuncionActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentanaFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, -1));

        btnVentanaClientes.setBackground(new java.awt.Color(255, 204, 0));
        btnVentanaClientes.setText("Clientes");
        btnVentanaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentanaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        btnVentanaBoleto.setBackground(new java.awt.Color(204, 102, 0));
        btnVentanaBoleto.setText("Boletos");
        btnVentanaBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaBoletoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentanaBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, -1));

        btnVentanaPeliculas.setBackground(new java.awt.Color(0, 102, 153));
        btnVentanaPeliculas.setText("Peliculas");
        btnVentanaPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaPeliculasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentanaPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/imagenes/MainMenu.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 530, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentanaBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaBoletoActionPerformed
        CompraBoletosWindow boletos = new CompraBoletosWindow();
        boletos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaBoletoActionPerformed

    private void btnVentanaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaClientesActionPerformed
        ClientesWindow clientes = new ClientesWindow();
        clientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaClientesActionPerformed

    private void btnVentanaPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaPeliculasActionPerformed
        VistasCartelera cartelera = new VistasCartelera();
        cartelera.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaPeliculasActionPerformed

    private void btnVentanaFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaFuncionActionPerformed
        FuncionesWindow funcion = new FuncionesWindow();
        funcion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaFuncionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoletos;
    private javax.swing.JButton btnBoletos1;
    private javax.swing.JButton btnBoletos2;
    private javax.swing.JButton btnBoletos3;
    private javax.swing.JButton btnBoletos4;
    private javax.swing.JButton btnBoletos5;
    private javax.swing.JButton btnBoletos6;
    private javax.swing.JButton btnBoletos7;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnClientes1;
    private javax.swing.JButton btnClientes2;
    private javax.swing.JButton btnClientes3;
    private javax.swing.JButton btnClientes4;
    private javax.swing.JButton btnClientes5;
    private javax.swing.JButton btnClientes6;
    private javax.swing.JButton btnClientes7;
    private javax.swing.JButton btnFunciones;
    private javax.swing.JButton btnFunciones1;
    private javax.swing.JButton btnFunciones2;
    private javax.swing.JButton btnFunciones3;
    private javax.swing.JButton btnFunciones4;
    private javax.swing.JButton btnFunciones5;
    private javax.swing.JButton btnFunciones6;
    private javax.swing.JButton btnFunciones7;
    private javax.swing.JButton btnPeliculas;
    private javax.swing.JButton btnPeliculas1;
    private javax.swing.JButton btnPeliculas2;
    private javax.swing.JButton btnPeliculas3;
    private javax.swing.JButton btnPeliculas4;
    private javax.swing.JButton btnPeliculas5;
    private javax.swing.JButton btnPeliculas6;
    private javax.swing.JButton btnPeliculas7;
    private javax.swing.JButton btnVentanaBoleto;
    private javax.swing.JButton btnVentanaClientes;
    private javax.swing.JButton btnVentanaFuncion;
    private javax.swing.JButton btnVentanaPeliculas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
