/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import accesoDatos.ConexionSQL;
/**
 *
 * @author melin
 */
public class PeliculasWindow extends javax.swing.JFrame {

    /**
     * Creates new form PeliculasWindow
     */
    public PeliculasWindow() {
        initComponents();
        cargarPeliculas(); // Llenar la tabla al abrir la ventana
    }
private void cargarPeliculas() {
    try {
        Connection conn = ConexionSQL.conectar();
        String query = "SELECT ID_Pelicula , Titulo, Genero, Clasificacion FROM Pelicula";
        PreparedStatement stmt = conn.prepareStatement(query);
        ResultSet rs = stmt.executeQuery();

        // Definir el modelo con los nombres de columna que deseas
        DefaultTableModel model = new DefaultTableModel(
            new Object[] { "ID_Pelicula", "Titulo", "Genero", "Clasificacion" }, 0
        );

        // Llenar el modelo con los datos del ResultSet
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("ID_Pelicula"),
                rs.getString("Titulo"),
                rs.getString("Genero"),
                rs.getString("Clasificacion")
            });
        }

        // Asignar el modelo a la tabla
        tblPeliculas.setModel(model);

        rs.close();
        stmt.close();
        conn.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar películas: " + ex.getMessage());
    }
}

         private void agregarPelicula() {
        try {
            Connection conn = ConexionSQL.conectar();
            String query = "INSERT INTO Peliculas (titulo, genero, duracion) VALUES (?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, txtTitulo.getText());
            stmt.setString(2, txtGenero.getText());
            stmt.setInt(3, Integer.parseInt(txtDuracion.getText()));
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Película agregada correctamente.");
            stmt.close();
            conn.close();
            cargarPeliculas();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar película: " + ex.getMessage());
        }
    }

    private void actualizarPelicula() {
        try {
            Connection conn = ConexionSQL.conectar();
            String query = "UPDATE Peliculas SET titulo=?, genero=?, duracion=? WHERE id=?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, txtTitulo.getText());
            stmt.setString(2, txtGenero.getText());
            stmt.setInt(3, Integer.parseInt(txtDuracion.getText()));
            stmt.setInt(4, Integer.parseInt(txtID.getText()));
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Película actualizada correctamente.");
            stmt.close();
            conn.close();
            cargarPeliculas();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar película: " + ex.getMessage());
        }
    }

    private void eliminarPelicula() {
        try {
            Connection conn = ConexionSQL.conectar();
            String query = "DELETE FROM Peliculas WHERE id=?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setInt(1, Integer.parseInt(txtID.getText()));
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Película eliminada correctamente.");
            stmt.close();
            conn.close();
            cargarPeliculas();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar película: " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPeliculas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeliculas = new javax.swing.JTable();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        lblDuracion = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeliculas.setText("Películas disponibles en el Cine");
        jPanel1.add(lblPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 30));

        tblPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPeliculas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 540, 160));

        lblID.setText("ID: ");
        jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        lblNombre.setText("Título:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        lblGenero.setText("Género: ");
        jPanel1.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));
        jPanel1.add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        lblDuracion.setText("Duración: ");
        jPanel1.add(lblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));
        jPanel1.add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        btnAgregar.setText("Agregar");
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        btnActualizar.setText("Actualizar");
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        btnCargar.setText("Cargar");
        jPanel1.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeliculasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeliculasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeliculasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeliculasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeliculasWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeliculas;
    private javax.swing.JTable tblPeliculas;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
