/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import accesoDatos.ConexionSQL;
/**
 *
 * @author melin
 */
public class PeliculasWindow extends javax.swing.JFrame {

    /**
     * Creates new form PeliculasWindow
     */
    public PeliculasWindow() {
        initComponents();
        cargarPeliculas(); // Llenar la tabla al abrir la ventana
    }
private void cargarPeliculas() {
    try {
        Connection conn = ConexionSQL.conectar();
        String query = "SELECT ID_Pelicula , Titulo, Genero, Clasificacion FROM Pelicula";
        PreparedStatement stmt = conn.prepareStatement(query);
        ResultSet rs = stmt.executeQuery();

        // Definir el modelo con los nombres de columna que deseas
        DefaultTableModel model = new DefaultTableModel(
            new Object[] { "ID_Pelicula", "Titulo", "Genero", "Clasificacion" }, 0
        );

        // Llenar el modelo con los datos del ResultSet
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("ID_Pelicula"),
                rs.getString("Titulo"),
                rs.getString("Genero"),
                rs.getString("Clasificacion")
            });
        }

        // Asignar el modelo a la tabla
        tblPeliculas.setModel(model);

        rs.close();
        stmt.close();
        conn.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar películas: " + ex.getMessage());
    }
}

         private void agregarPelicula() {
        try {
            Connection conn = ConexionSQL.conectar();
            String query = "INSERT INTO Peliculas (titulo, genero, duracion) VALUES (?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, txtClasificacion.getText());
            stmt.setString(2, txtClasificacion.getText());
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Película agregada correctamente.");
            stmt.close();
            conn.close();
            cargarPeliculas();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar película: " + ex.getMessage());
        }
    }

    private void actualizarPelicula() {
        try {
            Connection conn = ConexionSQL.conectar();
            String query = "UPDATE Peliculas SET titulo=?, genero=?, duracion=? WHERE id=?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, txtClasificacion.getText());
            stmt.setString(2, txtClasificacion.getText());
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Película actualizada correctamente.");
            stmt.close();
            conn.close();
            cargarPeliculas();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar película: " + ex.getMessage());
        }
    }

    private void eliminarPelicula() {
        try {
            Connection conn = ConexionSQL.conectar();
            String query = "DELETE FROM Peliculas WHERE id=?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Película eliminada correctamente.");
            stmt.close();
            conn.close();
            cargarPeliculas();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar película: " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeliculas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnFunciones = new javax.swing.JButton();
        txtClasificacion = new javax.swing.JTextField();
        lblClasificacion = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        txtTitulo1 = new javax.swing.JTextField();
        lblGenero1 = new javax.swing.JLabel();
        txtGenero1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        DropDownPeliculas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Peliculas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPeliculas.setBackground(new java.awt.Color(0, 204, 153));
        tblPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPeliculas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, 350));

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Actualizar");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        btnFunciones.setBackground(new java.awt.Color(204, 153, 0));
        btnFunciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFunciones.setText("Funciones");
        btnFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionesActionPerformed(evt);
            }
        });
        jPanel2.add(btnFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 120, -1));
        jPanel2.add(txtClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 220, -1));

        lblClasificacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblClasificacion.setForeground(new java.awt.Color(255, 255, 255));
        lblClasificacion.setText("Clasificación");
        jPanel2.add(lblClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 120, -1));
        lblClasificacion.getAccessibleContext().setAccessibleName("lblTitulo");

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setText("Titulo");
        jPanel2.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 50, -1));
        jPanel2.add(txtTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 220, -1));

        lblGenero1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGenero1.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero1.setText("Género");
        jPanel2.add(lblGenero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 60, -1));
        jPanel2.add(txtGenero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 220, -1));

        jButton4.setBackground(new java.awt.Color(204, 153, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("Eliminar");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 110, -1));

        DropDownPeliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(DropDownPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 390, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/imagenes/cinema-background-wr0kcgjhcfsledgt.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 510));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionesActionPerformed
        FuncionesWindow funciones = new FuncionesWindow();
        funciones.setVisible(true);
        setVisible(true);
    }//GEN-LAST:event_btnFuncionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeliculasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeliculasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeliculasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeliculasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeliculasWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DropDownPeliculas;
    private javax.swing.JButton btnFunciones;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClasificacion;
    private javax.swing.JLabel lblGenero1;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTable tblPeliculas;
    private javax.swing.JTextField txtClasificacion;
    private javax.swing.JTextField txtGenero1;
    private javax.swing.JTextField txtTitulo1;
    // End of variables declaration//GEN-END:variables
}
