/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import accesoDatos.ConexionSQL;
import java.sql.Connection;
//import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;
import accesoDatos.ConexionSQL;
import java.beans.Statement;
import java.io.FileOutputStream;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.Element;


/**
 *
 * @author contr
 */
public class ReportesVentas extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public ReportesVentas() {
        initComponents();
        
        cargaTableDefecto();
    }
    
    
private void cargaTableDefecto() {
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"ID Compra", "Cantidad", "Fecha de Compra", "ID de la funcion", "Pelicula", "Sala"}, 0
    );
    tblReporteVentaTiquetes.setModel(model);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAplicar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporteVentaTiquetes = new javax.swing.JTable();
        btnExportar = new javax.swing.JButton();
        jYearChooserFiltro = new com.toedter.calendar.JYearChooser();
        btnMenu1 = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Reporte de Venta de Tiquetes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        btnAplicar.setBackground(new java.awt.Color(0, 51, 204));
        btnAplicar.setForeground(new java.awt.Color(255, 255, 255));
        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 170, 60));

        tblReporteVentaTiquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReporteVentaTiquetes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 910, -1));

        btnExportar.setBackground(new java.awt.Color(0, 51, 204));
        btnExportar.setForeground(new java.awt.Color(255, 255, 255));
        btnExportar.setText("Exportar en Excel");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        jPanel1.add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 170, 60));
        jPanel1.add(jYearChooserFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 110, 50));

        btnMenu1.setBackground(new java.awt.Color(0, 51, 204));
        btnMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu1.setText("Menú Principal");
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 170, 60));

        btnPDF.setBackground(new java.awt.Color(0, 51, 204));
        btnPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnPDF.setText("Exportar en PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });
        jPanel1.add(btnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 180, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
    int yearoSeleccionado = jYearChooserFiltro.getYear(); // Obtener el año elegido

    try (Connection conn = ConexionSQL.conectar()) {
        String query = "SELECT * FROM vw_reporte_venta_tiquetes WHERE YEAR(Fecha_Compra) = ? ORDER BY Cantidad DESC;";
        PreparedStatement stmt = conn.prepareStatement(query);
        stmt.setInt(1, yearoSeleccionado); // Establecer parámetro del año
        ResultSet rs = stmt.executeQuery();

        // Modelo con columnas específicas
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID_Compra", "Cantidad", "Fecha_Compra", "ID_Funcion", "Pelicula", "Sala"}, 0
        );

        // Llenar la tabla con los resultados
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("ID_Compra"),
                rs.getInt("Cantidad"),
                rs.getDate("Fecha_Compra"),
                rs.getInt("ID_Funcion"),
                rs.getString("Pelicula"),
                rs.getInt("Sala")
            });
        }

        tblReporteVentaTiquetes.setModel(model);

        rs.close();
        stmt.close();
        JOptionPane.showMessageDialog(this, "Reporte generado para el año " + yearoSeleccionado);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al aplicar filtro por año: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
    try {
        // Crear un libro de Excel
        org.apache.poi.ss.usermodel.Workbook workbook = new org.apache.poi.xssf.usermodel.XSSFWorkbook();
        org.apache.poi.ss.usermodel.Sheet sheet = workbook.createSheet("Reporte de Ventas");

        // Encabezados
        org.apache.poi.ss.usermodel.Row headerRow = sheet.createRow(0);
        for (int i = 0; i < tblReporteVentaTiquetes.getColumnCount(); i++) {
            headerRow.createCell(i).setCellValue(tblReporteVentaTiquetes.getColumnName(i));
        }

        // Datos
        for (int i = 0; i < tblReporteVentaTiquetes.getRowCount(); i++) {
            org.apache.poi.ss.usermodel.Row row = sheet.createRow(i + 1);
            for (int j = 0; j < tblReporteVentaTiquetes.getColumnCount(); j++) {
                Object value = tblReporteVentaTiquetes.getValueAt(i, j);
                row.createCell(j).setCellValue(value != null ? value.toString() : "");
            }
        }

        // Diálogo para elegir ruta y nombre de archivo
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Guardar reporte como...");
        fileChooser.setSelectedFile(new java.io.File("ReporteVentasTiquetes.xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            try (java.io.FileOutputStream fileOut = new java.io.FileOutputStream(fileToSave)) {
                workbook.write(fileOut);
                workbook.close();
                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente en: \n" + fileToSave.getAbsolutePath());
            }
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al exportar Excel: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        MenuAdmin menu = new MenuAdmin();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
  try {
        // Crear documento PDF
        com.lowagie.text.Document document = new com.lowagie.text.Document();

        // Abrir JFileChooser para elegir ubicación y nombre del archivo
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Guardar reporte como PDF");
        fileChooser.setSelectedFile(new java.io.File("ReporteVentasTiquetes.pdf"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection != javax.swing.JFileChooser.APPROVE_OPTION) return;

        // Obtener el archivo seleccionado por el usuario
        java.io.File fileToSave = fileChooser.getSelectedFile();

        // Crear el writer para generar el archivo PDF
        com.lowagie.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(fileToSave));
        document.open();

        // Agregar título
        com.lowagie.text.Paragraph title = new com.lowagie.text.Paragraph("Reporte de Venta de Tiquetes\n\n");
        title.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
        document.add(title);

        // Crear tabla PDF con el mismo número de columnas que la JTable
        com.lowagie.text.pdf.PdfPTable pdfTable = new com.lowagie.text.pdf.PdfPTable(tblReporteVentaTiquetes.getColumnCount());
        pdfTable.setWidthPercentage(100);

        // Agregar encabezados de columna
        for (int col = 0; col < tblReporteVentaTiquetes.getColumnCount(); col++) {
            pdfTable.addCell(tblReporteVentaTiquetes.getColumnName(col));
        }

        // Agregar datos de las filas
        for (int row = 0; row < tblReporteVentaTiquetes.getRowCount(); row++) {
            for (int col = 0; col < tblReporteVentaTiquetes.getColumnCount(); col++) {
                Object value = tblReporteVentaTiquetes.getValueAt(row, col);
                pdfTable.addCell(value != null ? value.toString() : "");
            }
        }

        // Agregar la tabla al documento y cerrar
        document.add(pdfTable);
        document.close();

        JOptionPane.showMessageDialog(this, "Reporte exportado exitosamente:\n" + fileToSave.getAbsolutePath());

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al exportar PDF: " + e.getMessage());
    }
    }//GEN-LAST:event_btnPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JYearChooser jYearChooserFiltro;
    private javax.swing.JTable tblReporteVentaTiquetes;
    // End of variables declaration//GEN-END:variables
}
