/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import accesoDatos.ConexionSQL;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.sql.CallableStatement;
import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import javax.swing.JFileChooser;
import java.io.FileOutputStream;
import java.io.File;




/**
 *
 * @author contr
 */
public class ReporteClienteTiquete extends javax.swing.JFrame {

    /**
     * Creates new form ReporteClienteTiquete
     */
    public ReporteClienteTiquete() {
        initComponents();
        
            // Establecer el año 2025 como valor predeterminado
    jYearChooserCliente.setYear(2025);

    // Ejecutar automáticamente el procedimiento con el año 2025
    int anioInicial = 2025;

    try (Connection conn = ConexionSQL.conectar()) {
        String sql = "{CALL sp_ClientesEstrella(?)}";
        CallableStatement stmt = conn.prepareCall(sql);
        stmt.setInt(1, anioInicial);

        ResultSet rs = stmt.executeQuery();

        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID Cliente", "Nombre", "Apellido", "Tipo Membresía", "Año", "Total Compras"}, 0
        );

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("ID_Cliente"),
                rs.getString("Nombre"),
                rs.getString("Apellido"),
                rs.getString("Tipo Membresía"),
                rs.getInt("Año"),
                rs.getInt("Total Compras")
            });
        }

        tblReporteClientes.setModel(model);
        rs.close();
        stmt.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar el reporte inicial: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnExportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporteClientes = new javax.swing.JTable();
        btnAplicar = new javax.swing.JButton();
        jYearChooserCliente = new com.toedter.calendar.JYearChooser();
        btnMenuP2 = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.setForeground(new java.awt.Color(51, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reporte de Clientes Estrella");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        btnExportar.setBackground(new java.awt.Color(0, 0, 204));
        btnExportar.setForeground(new java.awt.Color(255, 255, 255));
        btnExportar.setText("Exportar Excel");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        jPanel1.add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 170, 60));

        tblReporteClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReporteClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 910, 280));

        btnAplicar.setBackground(new java.awt.Color(0, 0, 204));
        btnAplicar.setForeground(new java.awt.Color(255, 255, 255));
        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 170, 60));
        jPanel1.add(jYearChooserCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 100, 50));

        btnMenuP2.setBackground(new java.awt.Color(0, 0, 204));
        btnMenuP2.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuP2.setText("Menú Principal");
        btnMenuP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuP2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 170, 60));

        btnPDF.setBackground(new java.awt.Color(0, 0, 204));
        btnPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnPDF.setText("Exportar PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });
        jPanel1.add(btnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 160, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
    try {
        // Crear el libro de Excel
        Workbook workbook = new XSSFWorkbook();
        Sheet sheet = workbook.createSheet("Clientes Estrella");

        // Crear fila de encabezado
        Row headerRow = sheet.createRow(0);
        for (int i = 0; i < tblReporteClientes.getColumnCount(); i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(tblReporteClientes.getColumnName(i));
        }

        // Agregar los datos
        for (int i = 0; i < tblReporteClientes.getRowCount(); i++) {
            Row row = sheet.createRow(i + 1);
            for (int j = 0; j < tblReporteClientes.getColumnCount(); j++) {
                Object value = tblReporteClientes.getValueAt(i, j);
                row.createCell(j).setCellValue(value != null ? value.toString() : "");
            }
        }

        // Diálogo para guardar archivo
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar reporte como...");
        fileChooser.setSelectedFile(new File("ClientesEstrella.xlsx"));
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            try (FileOutputStream fileOut = new FileOutputStream(fileToSave)) {
                workbook.write(fileOut);
                workbook.close();
                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente en:\n" + fileToSave.getAbsolutePath());
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al exportar: " + e.getMessage());
    }

    // Ir al menú principal
    MenuAdmin menu = new MenuAdmin();
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
    int anioSeleccionado = jYearChooserCliente.getYear();  // Obtener el año del selector

    try (Connection conn = ConexionSQL.conectar()) {
        String sql = "{CALL sp_ClientesEstrella(?)}";
        CallableStatement stmt = conn.prepareCall(sql);
        stmt.setInt(1, anioSeleccionado);  // Pasar el año como parámetro

        ResultSet rs = stmt.executeQuery();

        // Modelo actualizado con nombres de columnas que coinciden con el procedimiento
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID Cliente", "Nombre", "Apellido", "Tipo Membresía", "Año", "Total Compras"}, 0
        );

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("ID_Cliente"),
                rs.getString("Nombre"),
                rs.getString("Apellido"),
                rs.getString("Tipo Membresía"),
                rs.getInt("Año"),
                rs.getInt("Total Compras")
            });
        }

        tblReporteClientes.setModel(model);
        rs.close();
        stmt.close();

        JOptionPane.showMessageDialog(this, "Reporte generado para el año " + anioSeleccionado);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al generar el reporte: " + e.getMessage());
    }     
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void btnMenuP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuP2ActionPerformed
       MenuAdmin menu = new MenuAdmin();
       menu.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnMenuP2ActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
    Document document = new Document();
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar reporte como...");
    fileChooser.setSelectedFile(new File("ClientesEstrella.pdf"));
    
    int userSelection = fileChooser.showSaveDialog(this);
    
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(fileToSave));
            document.open();
            document.add(new Paragraph("Reporte de Clientes Estrella"));
            document.add(new Paragraph(" ")); // espacio

            PdfPTable table = new PdfPTable(tblReporteClientes.getColumnCount());
            
            // Agregar encabezados
            for (int i = 0; i < tblReporteClientes.getColumnCount(); i++) {
                table.addCell(tblReporteClientes.getColumnName(i));
            }

            // Agregar filas
            for (int row = 0; row < tblReporteClientes.getRowCount(); row++) {
                for (int col = 0; col < tblReporteClientes.getColumnCount(); col++) {
                    Object value = tblReporteClientes.getValueAt(row, col);
                    table.addCell(value != null ? value.toString() : "");
                }
            }

            document.add(table);
            document.close();

            JOptionPane.showMessageDialog(this, "Archivo PDF guardado exitosamente en:\n" + fileToSave.getAbsolutePath());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al exportar a PDF: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteClienteTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteClienteTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteClienteTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteClienteTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteClienteTiquete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnMenuP2;
    private javax.swing.JButton btnPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JYearChooser jYearChooserCliente;
    private javax.swing.JTable tblReporteClientes;
    // End of variables declaration//GEN-END:variables
}
