/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import accesoDatos.VistaCarteleraDAO;
import entidades.VistaCartelera;
import java.awt.BorderLayout;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author contr
 */
public class V_cartelera extends javax.swing.JFrame {

    /**
     * Creates new form V_cartelera
     */
    public V_cartelera() {
        initComponents();
        cargarCartelera();
        cargarComboPeliculas();
    }
    
         
        private void cargarCartelera() {
    try {
        VistaCarteleraDAO dao = new VistaCarteleraDAO();
        List<VistaCartelera> lista = dao.obtenerCartelera();

        String[] columnas = {"Título", "Género", "Clasificación", "Horarios"};
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(null, columnas);

        for (VistaCartelera vc : lista) {
            model.addRow(new Object[]{
                vc.getTitulo(),
                vc.getGenero(),
                vc.getClasificacion(),
                vc.getHorarios()
            });
        }

        DefaultTableModel.setModel(model);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar cartelera: " + e.getMessage());
    }
}
        
       private void cargarComboPeliculas() {
    try {
        VistaCarteleraDAO dao = new VistaCarteleraDAO();
        List<String> titulos = dao.obtenerTitulosPeliculas();

        for (String titulo : titulos) {
            ElejirPelicula.addItem(titulo); // Asegurate de que tu JComboBox se llama así
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar títulos: " + e.getMessage());
    }
}
        
            private void aplicarFiltro() {
    String tituloSeleccionado = ElejirPelicula.getSelectedItem().toString();

    try {
        VistaCarteleraDAO dao = new VistaCarteleraDAO();
        List<VistaCartelera> lista = dao.obtenerCartelera(); // o crea un método nuevo que filtre desde SQL

        DefaultTableModel model = new DefaultTableModel(new Object[]{"Título", "Género", "Clasificación", "Horarios"}, 0);

        for (VistaCartelera vc : lista) {
            if (vc.getTitulo().equalsIgnoreCase(tituloSeleccionado)) {
                model.addRow(new Object[]{
                    vc.getTitulo(),
                    vc.getGenero(),
                    vc.getClasificacion(),
                    vc.getHorarios()
                });
            }
        }

        DefaultTableModel.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al aplicar filtro: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel = new javax.swing.JTable();
        ElejirPelicula = new javax.swing.JComboBox<>();
        btnFiltroPelicula = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));

        panelFondo.setBackground(new java.awt.Color(255, 102, 0));
        panelFondo.setForeground(new java.awt.Color(255, 102, 0));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cartelera");
        panelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        DefaultTableModel.setBackground(new java.awt.Color(102, 255, 102));
        DefaultTableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(DefaultTableModel);

        panelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 620, 270));

        ElejirPelicula.setBackground(new java.awt.Color(0, 51, 204));
        ElejirPelicula.setForeground(new java.awt.Color(255, 255, 255));
        ElejirPelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elije tu pelicula" }));
        ElejirPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElejirPeliculaMouseClicked(evt);
            }
        });
        panelFondo.add(ElejirPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 230, -1));

        btnFiltroPelicula.setBackground(new java.awt.Color(0, 0, 204));
        btnFiltroPelicula.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltroPelicula.setText("Aplicar Filtro");
        btnFiltroPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroPeliculaActionPerformed(evt);
            }
        });
        panelFondo.add(btnFiltroPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 140, 50));

        btnMenu.setBackground(new java.awt.Color(0, 0, 204));
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("Menu Principal");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        panelFondo.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ElejirPeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElejirPeliculaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ElejirPeliculaMouseClicked

    private void btnFiltroPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroPeliculaActionPerformed
        aplicarFiltro();
    }//GEN-LAST:event_btnFiltroPeliculaActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_cartelera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DefaultTableModel;
    private javax.swing.JComboBox<String> ElejirPelicula;
    private javax.swing.JButton btnFiltroPelicula;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
