/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import accesoDatos.VistaCarteleraDAO;
import entidades.VistaCartelera;
import java.awt.BorderLayout;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author contr
 */
public class VistasCartelera extends javax.swing.JFrame {

    /**
     * Creates new form VistasCine
     */
    public VistasCartelera() {
        initComponents();
        cargarCartelera();
        cargarComboPeliculas();
         setBackgroundImage();
    }
    
     private void setBackgroundImage() {
        // Ruta de la imagen que deseas usar
        ImageIcon backgroundImage = new ImageIcon(getClass().getResource("\"C:\\Users\\melin\\OneDrive\\Escritorio\\CINE-MARZO-2023-1.png\""));
        Image image = backgroundImage.getImage(); // Convertimos la imagen en un objeto Image

        // Establecer la imagen de fondo en el JPanel
        panelFondo.setLayout(new BorderLayout()) ;  // Usamos BorderLayout para que ocupe toda la ventana
        panelFondo.add(new JLabel(new ImageIcon(image)), BorderLayout.CENTER);
        
        // Establecer el fondo del JFrame como el JPanel con la imagen
        this.setContentPane(panelFondo);
    }


    private void cargarCartelera() {
    try {
        VistaCarteleraDAO dao = new VistaCarteleraDAO();
        List<VistaCartelera> lista = dao.obtenerCartelera();

        String[] columnas = {"Título", "Género", "Clasificación", "Horarios"};
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(null, columnas);

        for (VistaCartelera vc : lista) {
            model.addRow(new Object[]{
                vc.getTitulo(),
                vc.getGenero(),
                vc.getClasificacion(),
                vc.getHorarios()
            });
        }

        DefaultTableModel.setModel(model);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar cartelera: " + e.getMessage());
    }
}
    
    private void cargarComboPeliculas() {
    try {
        VistaCarteleraDAO dao = new VistaCarteleraDAO();
        List<String> titulos = dao.obtenerTitulosPeliculas();

        for (String titulo : titulos) {
            ElejirPelicula.addItem(titulo); // Asegurate de que tu JComboBox se llama así
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar títulos: " + e.getMessage());
    }
}
    
    private void aplicarFiltro() {
    String tituloSeleccionado = ElejirPelicula.getSelectedItem().toString();

    try {
        VistaCarteleraDAO dao = new VistaCarteleraDAO();
        List<VistaCartelera> lista = dao.obtenerCartelera(); // o crea un método nuevo que filtre desde SQL

        DefaultTableModel model = new DefaultTableModel(new Object[]{"Título", "Género", "Clasificación", "Horarios"}, 0);

        for (VistaCartelera vc : lista) {
            if (vc.getTitulo().equalsIgnoreCase(tituloSeleccionado)) {
                model.addRow(new Object[]{
                    vc.getTitulo(),
                    vc.getGenero(),
                    vc.getClasificacion(),
                    vc.getHorarios()
                });
            }
        }

        DefaultTableModel.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al aplicar filtro: " + e.getMessage());
    }
}
  }
    




    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        ElejirPelicula = new javax.swing.JComboBox<>();
        btnFiltroPelicula1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 102, 0));
        panelFondo.setForeground(new java.awt.Color(255, 102, 0));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Cartelera");
        panelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        DefaultTableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(DefaultTableModel);

        panelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 880, 120));

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Menu Principal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelFondo.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, 140, 50));

        ElejirPelicula.setBackground(new java.awt.Color(0, 51, 204));
        ElejirPelicula.setForeground(new java.awt.Color(255, 255, 255));
        ElejirPelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elije tu pelicula" }));
        ElejirPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElejirPeliculaMouseClicked(evt);
            }
        });
        panelFondo.add(ElejirPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 180, 230, -1));

        btnFiltroPelicula1.setBackground(new java.awt.Color(0, 0, 204));
        btnFiltroPelicula1.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltroPelicula1.setText("Aplicar Filtro");
        btnFiltroPelicula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroPelicula1ActionPerformed(evt);
            }
        });
        panelFondo.add(btnFiltroPelicula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       MainMenu menu = new MainMenu();
       menu.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ElejirPeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElejirPeliculaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ElejirPeliculaMouseClicked

    private void btnFiltroPelicula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroPelicula1ActionPerformed
        aplicarFiltro();
    }//GEN-LAST:event_btnFiltroPelicula1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistasCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistasCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistasCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistasCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistasCartelera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DefaultTableModel;
    private javax.swing.JComboBox<String> ElejirPelicula;
    private javax.swing.JButton btnFiltroPelicula1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
